import type { Metadata } from "next";
import localFont from "next/font/local";
import Sidebar from "@/widgets/sidebar/ui/Sidebar";
import "./globals.css";
import Header from "@/widgets/header/ui/Header";
import DefaultPageWrapper from "./wrapper/DefaultPageWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <Header />
        <Sidebar />
        <DefaultPageWrapper>{children}</DefaultPageWrapper>
      </body>
    </html>
  );
}
